name: lpncode
description: "A Flutter package for generating, scanning, and managing License Plate Number (LPN) barcodes in warehouse management systems."
version: 0.1.2
homepage: "https://github.com/ab22593k/lpncode"
environment:
  sdk: "^3.5.4"

dependencies:
  json: ^0.20.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
