name: lpncode
description: "A Flutter package for generating, scanning, and managing License Plate Number (LPN) barcodes in warehouse management systems."
version: 0.1.0
homepage: "https://github.com/ab22593k/lpncode"
environment:
  sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.7
