name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Also trigger on release tags
  release:
    types: [published]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: windows-latest
            flutter_path: ${env:LOCALAPPDATA}/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  package-analysis:
    name: Package analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check publish warnings
        run: flutter pub publish --dry-run

      - name: Verify package score
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.CODECOV }}

  publish:
    name: Publish to pub.dev
    needs: [test, package-analysis]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Publish Requirements
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --force
